"""folder_ parent id optional

Revision ID: ed88339d87cb
Revises: be30ff31f05d
Create Date: 2024-11-09 20:21:46.104993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed88339d87cb'
down_revision = 'be30ff31f05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('folders', schema=None) as batch_op:
        batch_op.alter_column('parent_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
